#pragma once
#include <stdint.h>
#include <vector>
#include "comm/RestPacket.h"
#include "comm/CommunicationDefinitions.h"
#include "comm/Joystick.h"
#include "comm/TagPosition.h"
#include "comm/FieldPosition.h"
#include "comm/Obstacle.h"
#include "comm/Vision.h"
#include "comm/VisionCommand.h"
#include "comm/Realsense.h"
#include "comm/Identifier.h"
#include "comm/RobotState.h"
#include "comm/DataServer.h"
#include "comm/Dashboard.h"
#include "comm/MotorInfo.h"
